spring.application.name=product-pricing-engine
spring.profiles.active=prod
server.port=8080
logging.file.name=./log/product-pricing-engine.log

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms
spring.data.redis.lettuce.pool.max-active=10
spring.data.redis.lettuce.pool.max-idle=5
spring.data.redis.lettuce.pool.min-idle=2

pricing.rules.competitive.enabled=true
pricing.rules.competitive.priority=100
pricing.rules.competitive.adjustment-percentage=3.0

pricing.rules.inventory.enabled=true
pricing.rules.inventory.priority=200
pricing.rules.inventory.low-stock-threshold=100
pricing.rules.inventory.low-stock-percentage=5.0
pricing.rules.inventory.price-increase-percentage=10.0

pricing.rules.loyalty.enabled=true
pricing.rules.loyalty.priority=300
pricing.rules.loyalty.gold-member-discount=10.0
pricing.rules.loyalty.platinum-member-discount=15.0

pricing.rules.festival.enabled=true
pricing.rules.festival.priority=400
pricing.rules.festival.default-discount=15.0

pricing.cache.local.enabled=true
pricing.cache.local.ttl-seconds=60
pricing.cache.local.max-size=10000

pricing.cache.distributed.enabled=true
pricing.cache.distributed.ttl-seconds=300
pricing.cache.distributed.key-prefix=pricing:

pricing.festivals[0].name=Republic Day
pricing.festivals[0].date=01-26
pricing.festivals[0].discount=20.0

pricing.festivals[1].name=Independence Day
pricing.festivals[1].date=08-15
pricing.festivals[1].discount=15.0


management.endpoints.web.exposure.include=health,info,metrics
manangement.endpoint.health.show-details=always

logging.level.com.abc.pricing=DEBUG
logging.level.org.springframework.r2dbc=DEBUG

# Kafka Broker Address
spring.kafka.bootstrap-servers=localhost:9092

# Consumer Config
spring.kafka.consumer.group-id=price-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Producer Config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

crawler.scheduler.enabled=false
crawler.timeout-ms=10000
crawler.user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

