# ================= H2 DATABASE =================

spring.r2dbc.url=r2dbc:h2:mem:///testdb
spring.r2dbc.username=sa
spring.r2dbc.password=

# Optional JDBC (for console)
spring.datasource.url=jdbc:h2:mem:testdb

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Always initialize schema in local
spring.sql.init.mode=always